[project]
authors = ["rd4com <144297616+rd4com@users.noreply.github.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "mojo-new-web-framework"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0.dev2024102406,<25"
